language: clojure
lein: lein2
env:
  - JVM_OPTS="-Dspid.freeze.assets=true -Dspid.freeze.pages=true"
before_install: cp resources/config.sample.edn resources/config.edn
script: lein2 with-profile test midje
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
